plugins { id 'net.fabricmc.fabric-loom' version '1.15.5' }
apply from: rootProject.file('gradle/loader-common.gradle')
repositories { mavenCentral() }
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}
loom {
    accessWidenerPath.set(rootProject.file('common/src/main/resources/larion.accesswidener'))
    runs {
        client { runDir('run/client') }
        server { runDir('run/server'); programArg 'nogui' }
    }
}
