pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.neoforged.net/releases/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}
rootProject.name = 'larion'
def selected = providers.gradleProperty('loaders').getOrElse('fabric,neoforge,forge').split(',')
selected.each {
    if (!(it in ['fabric', 'neoforge', 'forge'])) throw new GradleException("Unknown loader: ${it}")
    include(it)
}
