plugins { id 'net.minecraftforge.gradle' version '7.0.29' }
apply from: rootProject.file('gradle/loader-common.gradle')
minecraft {
    accessTransformer = true
    runs {
        configureEach { args '--mixin.config=larion.mixins.json' }
        register('client') { workingDir = layout.projectDirectory.dir('run/client') }
        register('server') { workingDir = layout.projectDirectory.dir('run/server'); args '--nogui' }
    }
}
repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}
dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.5'
}
tasks.named('jar', Jar) { manifest.attributes['MixinConfigs'] = 'larion.mixins.json' }
