plugins { id 'net.neoforged.moddev' version '2.0.141' }
apply from: rootProject.file('gradle/loader-common.gradle')
neoForge {
    version = neoforge_version
    accessTransformers.from(file('src/main/resources/META-INF/accesstransformer.cfg'))
    runs {
        client { client(); gameDirectory = file('run/client') }
        server { server(); gameDirectory = file('run/server'); programArgument 'nogui' }
    }
    mods { larion { sourceSet sourceSets.main } }
}
